---

version: '3.7'

services:

  front:
    build:
      context: ./front
      args:
        REACT_APP_API_URL: http://localhost:3001
    network_mode: host

  api:
    build: ./api
    ports:
      - "3001:3001"
    env_file: ./api/.env
