---

name: API

on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/api.yaml'

defaults:
  run:
    working-directory: api/

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.15']
    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.15']
    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run test
